project_id = "yojlbxpbxfskcfzfoghs"

[functions.chat]
verify_jwt = false

[functions.scan-fertilizer]
verify_jwt = false

[functions.detect-disease]
verify_jwt = false

[functions.rag-answer]
verify_jwt = false
